apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  labels:
    operators.coreos.com/rh-service-binding-operator.openshift-operators: ""
  name: rh-service-binding-operator
  namespace: openshift-operators
spec:
  channel: stable
  installPlanApproval: Manual
  name: rh-service-binding-operator
  source: redhat-operators
  sourceNamespace: openshift-marketplace
  startingCSV: service-binding-operator.v1.0.0