apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  name: ibm-mas-visualinspection-operators
  namespace: openshift-marketplace
spec:
  displayName: IBM MAS Visual Inspection Catalog
  publisher: IBM
  description: Catalog Source for IBM Maximo Application Suite Visual Inspection
  sourceType: grpc
  image: wiotp-docker-local.artifactory.swg-devops.com/cpopen/ibm-mas-visualinspection-operator-catalog:latest
  updateStrategy:
    registryPoll:
      interval: 45m
  priority: 100