# Shared BAS system running on the masdeps1 cluster in IBM Cloud (MAS Development account)
# You may connect any development system to this configuration
---
apiVersion: v1
kind: Secret
type: opaque
metadata:
  name: bas-apikey
  namespace: "mas-maivs-core"
stringData:
  api_key: "yOm16VBxiXHkRnFH6p1G5j1HfJIMSAQTk2TITndNMIw1Xri1PcbP5B1gAdpIQiFn"
---
apiVersion: config.mas.ibm.com/v1
kind: BasCfg
metadata:
  name: "maivs-bas-system"
  namespace: "mas-maivs-core"
  labels:
    mas.ibm.com/configScope: system
    mas.ibm.com/instanceId: "maivs"
spec:
  displayName: UDS maivs
  config:
    url: "https://uds-endpoint-ibm-common-services.mvi-dal13-b3c-8x32-18312db33a3427c911e9adf447e95207-0000.us-south.containers.appdomain.cloud"
    contact:
      email: "saurabh.gupta@ibm.com"
      firstName: "Saurabh"
      lastName: "Gupta"
    credentials:
      secretName: bas-apikey
    segmentKey: "__omit_place_holder__e005803ac3896f696aca85c7b18fa86d58b72f6f"
  certificates:
    - alias: part1
      crt: |
        -----BEGIN CERTIFICATE-----
        MIIGMzCCBRugAwIBAgISBJjXM6e6r5Y97eI7AkK6GevMMA0GCSqGSIb3DQEBCwUA
        MDIxCzAJBgNVBAYTAlVTMRYwFAYDVQQKEw1MZXQncyBFbmNyeXB0MQswCQYDVQQD
        EwJSMzAeFw0yMjA0MDQxNTE1MDZaFw0yMjA3MDMxNTE1MDVaMEExPzA9BgNVBAMT
        Nm12aS1kYWwxMy1iM2MtOHgzMi51cy1zb3V0aC5jb250YWluZXJzLmFwcGRvbWFp
        bi5jbG91ZDCCASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoCggEBAMIV0wRsSmGT
        5jNZsiQ3eszmja3nc+SIFdjnMihq4f8OuOefXYFksERNVVLTx0s1MRT5GeVyUQls
        IqZR2Xaey1FIc6VtGHOl4PERe7h53LF3vVSfjYZjGmaVx7jAS8armL1J+za//ewd
        HudIZ8sPGeNFypRbxLycLKZzNdXMHgcnzBOLp2r+uUYoV1hY8disPjhw19cIOUpp
        0QKmMfbWkLZNUZkosPqQGKNb7ZUjtkgcd8j2vdwWHwfSs/wkeB7ahpg/Q1HleEZ7
        9WSDHbyG+PfE8MpWoVoHQvBeVQDuHt+uPwkEYfQp22W7WQNW53OUgnqfag/+/kV+
        9ophednmCh0CAwEAAaOCAzIwggMuMA4GA1UdDwEB/wQEAwIFoDAdBgNVHSUEFjAU
        BggrBgEFBQcDAQYIKwYBBQUHAwIwDAYDVR0TAQH/BAIwADAdBgNVHQ4EFgQU8cRQ
        E4Tn+jEQUT5Dl/cxhtxr52QwHwYDVR0jBBgwFoAUFC6zF7dYVsuuUAlA5h+vnYsU
        wsYwVQYIKwYBBQUHAQEESTBHMCEGCCsGAQUFBzABhhVodHRwOi8vcjMuby5sZW5j
        ci5vcmcwIgYIKwYBBQUHMAKGFmh0dHA6Ly9yMy5pLmxlbmNyLm9yZy8wggEBBgNV
        HREEgfkwgfaCXioubXZpLWRhbDEzLWIzYy04eDMyLTE4MzEyZGIzM2EzNDI3Yzkx
        MWU5YWRmNDQ3ZTk1MjA3LTAwMDAudXMtc291dGguY29udGFpbmVycy5hcHBkb21h
        aW4uY2xvdWSCXG12aS1kYWwxMy1iM2MtOHgzMi0xODMxMmRiMzNhMzQyN2M5MTFl
        OWFkZjQ0N2U5NTIwNy0wMDAwLnVzLXNvdXRoLmNvbnRhaW5lcnMuYXBwZG9tYWlu
        LmNsb3VkgjZtdmktZGFsMTMtYjNjLTh4MzIudXMtc291dGguY29udGFpbmVycy5h
        cHBkb21haW4uY2xvdWQwTAYDVR0gBEUwQzAIBgZngQwBAgEwNwYLKwYBBAGC3xMB
        AQEwKDAmBggrBgEFBQcCARYaaHR0cDovL2Nwcy5sZXRzZW5jcnlwdC5vcmcwggED
        BgorBgEEAdZ5AgQCBIH0BIHxAO8AdgBGpVXrdfqRIDC1oolp9PN9ESxBdL79SbiF
        q/L8cP5tRwAAAX/1W8b5AAAEAwBHMEUCIB/ilgntJFne02OLH/1UxmzBKeIhgogg
        PoF1lGyIld6oAiEA1bNEy1JRtqcseMvmYzYd7/GvHQEw63fEI+ecT2TEXhwAdQDf
        pV6raIJPH2yt7rhfTj5a6s2iEqRqXo47EsAgRFwqcwAAAX/1W8i9AAAEAwBGMEQC
        ID/+JxqgegsYQ/ABh09lwUg6w+V3Joc4hcM2fyitSn7zAiBUjKciqQe6ISJcSTJr
        yAg8byDQ6MuEbDf0PD5mRwoiNzANBgkqhkiG9w0BAQsFAAOCAQEAt2DIRZK5YpTm
        qrQ4XAap/XGzerbNqcoXMoslXuAq2sNjec2hxyBJUqYvuZCtA2xPFgHj9HdZHhpt
        GwKC9wbrZguDvgOdwmeM7//KpqGSRrP8id51pl4OwOehLIQj9dQNu7wOENjMoOIG
        9+nxu0rnzi2H9sgdcyNe+8U0t8PbDOFPo0D3QcbNHX5IlulNYfoR5AiEyzL9G9nE
        hbDsXshDlKVa/tPQcp/F6wOGkGTZU/0RHxlOs1yfKur+9XmA54pUyFdnhSGQLqXj
        iVrrNMN16KEXWvC24ebADEKwf4j21oGxVep6dNytionC0eIhC/h10miZvP2HL+xg
        NmsZyM483w==
        -----END CERTIFICATE-----
    - alias: part2
      crt: |
        -----BEGIN CERTIFICATE-----
        MIIFFjCCAv6gAwIBAgIRAJErCErPDBinU/bWLiWnX1owDQYJKoZIhvcNAQELBQAw
        TzELMAkGA1UEBhMCVVMxKTAnBgNVBAoTIEludGVybmV0IFNlY3VyaXR5IFJlc2Vh
        cmNoIEdyb3VwMRUwEwYDVQQDEwxJU1JHIFJvb3QgWDEwHhcNMjAwOTA0MDAwMDAw
        WhcNMjUwOTE1MTYwMDAwWjAyMQswCQYDVQQGEwJVUzEWMBQGA1UEChMNTGV0J3Mg
        RW5jcnlwdDELMAkGA1UEAxMCUjMwggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEK
        AoIBAQC7AhUozPaglNMPEuyNVZLD+ILxmaZ6QoinXSaqtSu5xUyxr45r+XXIo9cP
        R5QUVTVXjJ6oojkZ9YI8QqlObvU7wy7bjcCwXPNZOOftz2nwWgsbvsCUJCWH+jdx
        sxPnHKzhm+/b5DtFUkWWqcFTzjTIUu61ru2P3mBw4qVUq7ZtDpelQDRrK9O8Zutm
        NHz6a4uPVymZ+DAXXbpyb/uBxa3Shlg9F8fnCbvxK/eG3MHacV3URuPMrSXBiLxg
        Z3Vms/EY96Jc5lP/Ooi2R6X/ExjqmAl3P51T+c8B5fWmcBcUr2Ok/5mzk53cU6cG
        /kiFHaFpriV1uxPMUgP17VGhi9sVAgMBAAGjggEIMIIBBDAOBgNVHQ8BAf8EBAMC
        AYYwHQYDVR0lBBYwFAYIKwYBBQUHAwIGCCsGAQUFBwMBMBIGA1UdEwEB/wQIMAYB
        Af8CAQAwHQYDVR0OBBYEFBQusxe3WFbLrlAJQOYfr52LFMLGMB8GA1UdIwQYMBaA
        FHm0WeZ7tuXkAXOACIjIGlj26ZtuMDIGCCsGAQUFBwEBBCYwJDAiBggrBgEFBQcw
        AoYWaHR0cDovL3gxLmkubGVuY3Iub3JnLzAnBgNVHR8EIDAeMBygGqAYhhZodHRw
        Oi8veDEuYy5sZW5jci5vcmcvMCIGA1UdIAQbMBkwCAYGZ4EMAQIBMA0GCysGAQQB
        gt8TAQEBMA0GCSqGSIb3DQEBCwUAA4ICAQCFyk5HPqP3hUSFvNVneLKYY611TR6W
        PTNlclQtgaDqw+34IL9fzLdwALduO/ZelN7kIJ+m74uyA+eitRY8kc607TkC53wl
        ikfmZW4/RvTZ8M6UK+5UzhK8jCdLuMGYL6KvzXGRSgi3yLgjewQtCPkIVz6D2QQz
        CkcheAmCJ8MqyJu5zlzyZMjAvnnAT45tRAxekrsu94sQ4egdRCnbWSDtY7kh+BIm
        lJNXoB1lBMEKIq4QDUOXoRgffuDghje1WrG9ML+Hbisq/yFOGwXD9RiX8F6sw6W4
        avAuvDszue5L3sz85K+EC4Y/wFVDNvZo4TYXao6Z0f+lQKc0t8DQYzk1OXVu8rp2
        yJMC6alLbBfODALZvYH7n7do1AZls4I9d1P4jnkDrQoxB3UqQ9hVl3LEKQ73xF1O
        yK5GhDDX8oVfGKF5u+decIsH4YaTw7mP3GFxJSqv3+0lUFJoi5Lc5da149p90Ids
        hCExroL1+7mryIkXPeFM5TgO9r0rvZaBFOvV2z0gp35Z0+L4WPlbuEjN/lxPFin+
        HlUjr8gRsI3qfJOQFy/9rKIJR0Y/8Omwt/8oTWgy1mdeHmmjk7j1nYsvC9JSQ6Zv
        MldlTTKB3zhThV1+XWYp6rjd5JW1zbVWEkLNxE7GJThEUG3szgBVGP7pSWTUTsqX
        nLRbwHOoq7hHwg==
        -----END CERTIFICATE-----
    - alias: part3
      crt: |
        -----BEGIN CERTIFICATE-----
        MIIFazCCA1OgAwIBAgIRAIIQz7DSQONZRGPgu2OCiwAwDQYJKoZIhvcNAQELBQAw
        TzELMAkGA1UEBhMCVVMxKTAnBgNVBAoTIEludGVybmV0IFNlY3VyaXR5IFJlc2Vh
        cmNoIEdyb3VwMRUwEwYDVQQDEwxJU1JHIFJvb3QgWDEwHhcNMTUwNjA0MTEwNDM4
        WhcNMzUwNjA0MTEwNDM4WjBPMQswCQYDVQQGEwJVUzEpMCcGA1UEChMgSW50ZXJu
        ZXQgU2VjdXJpdHkgUmVzZWFyY2ggR3JvdXAxFTATBgNVBAMTDElTUkcgUm9vdCBY
        MTCCAiIwDQYJKoZIhvcNAQEBBQADggIPADCCAgoCggIBAK3oJHP0FDfzm54rVygc
        h77ct984kIxuPOZXoHj3dcKi/vVqbvYATyjb3miGbESTtrFj/RQSa78f0uoxmyF+
        0TM8ukj13Xnfs7j/EvEhmkvBioZxaUpmZmyPfjxwv60pIgbz5MDmgK7iS4+3mX6U
        A5/TR5d8mUgjU+g4rk8Kb4Mu0UlXjIB0ttov0DiNewNwIRt18jA8+o+u3dpjq+sW
        T8KOEUt+zwvo/7V3LvSye0rgTBIlDHCNAymg4VMk7BPZ7hm/ELNKjD+Jo2FR3qyH
        B5T0Y3HsLuJvW5iB4YlcNHlsdu87kGJ55tukmi8mxdAQ4Q7e2RCOFvu396j3x+UC
        B5iPNgiV5+I3lg02dZ77DnKxHZu8A/lJBdiB3QW0KtZB6awBdpUKD9jf1b0SHzUv
        KBds0pjBqAlkd25HN7rOrFleaJ1/ctaJxQZBKT5ZPt0m9STJEadao0xAH0ahmbWn
        OlFuhjuefXKnEgV4We0+UXgVCwOPjdAvBbI+e0ocS3MFEvzG6uBQE3xDk3SzynTn
        jh8BCNAw1FtxNrQHusEwMFxIt4I7mKZ9YIqioymCzLq9gwQbooMDQaHWBfEbwrbw
        qHyGO0aoSCqI3Haadr8faqU9GY/rOPNk3sgrDQoo//fb4hVC1CLQJ13hef4Y53CI
        rU7m2Ys6xt0nUW7/vGT1M0NPAgMBAAGjQjBAMA4GA1UdDwEB/wQEAwIBBjAPBgNV
        HRMBAf8EBTADAQH/MB0GA1UdDgQWBBR5tFnme7bl5AFzgAiIyBpY9umbbjANBgkq
        hkiG9w0BAQsFAAOCAgEAVR9YqbyyqFDQDLHYGmkgJykIrGF1XIpu+ILlaS/V9lZL
        ubhzEFnTIZd+50xx+7LSYK05qAvqFyFWhfFQDlnrzuBZ6brJFe+GnY+EgPbk6ZGQ
        3BebYhtF8GaV0nxvwuo77x/Py9auJ/GpsMiu/X1+mvoiBOv/2X/qkSsisRcOj/KK
        NFtY2PwByVS5uCbMiogziUwthDyC3+6WVwW6LLv3xLfHTjuCvjHIInNzktHCgKQ5
        ORAzI4JMPJ+GslWYHb4phowim57iaztXOoJwTdwJx4nLCgdNbOhdjsnvzqvHu7Ur
        TkXWStAmzOVyyghqpZXjFaH3pO3JLF+l+/+sKAIuvtd7u+Nxe5AW0wdeRlN8NwdC
        jNPElpzVmbUq4JUagEiuTDkHzsxHpFKVK7q4+63SM1N95R1NbdWhscdCb+ZAJzVc
        oyi3B43njTOQ5yOf+1CceWxG1bQVs5ZufpsMljq4Ui0/1lvh+wjChP4kqKOJ2qxq
        4RgqsahDYVvTH9w7jXbyLeiNdd8XM2w9U/t7y0Ff/9yi0GE44Za4rF2LN9d11TPA
        mRGunUHBcnWEvgJBQl9nJEiU0Zsnvgc/ubhPgXRR4Xq37Z0j4r7g1SgEEzwxA57d
        emyPxgcYxn/eR44/KJ4EBs+lVDR3veyJm+kXQ99b21/+jh5Xos1AnX5iItreGCc=
        -----END CERTIFICATE-----
