---
apiVersion: v1
kind: Secret
type: opaque
metadata:
  name: sls-registration-key
  namespace: "mas-maivs-core"
stringData:
  registrationKey: "4161810e-c56a-58d4-b8ff-67fbeb364aff"
---
apiVersion: config.mas.ibm.com/v1
kind: SlsCfg
metadata:
  name: "maivs-sls-system"
  namespace: "mas-maivs-core"
  labels:
    mas.ibm.com/configScope: system
    mas.ibm.com/instanceId: "maivs"
spec:
  displayName: SLS (maivs)
  config:
    url: "https://sls.ibm-sls.ocp411-18312db33a3427c911e9adf447e95207-0000.us-south.containers.appdomain.cloud"
    credentials:
      secretName: sls-registration-key
  certificates:
    - alias: ca
      crt: |
        -----BEGIN CERTIFICATE-----
        MIIDvDCCAqSgAwIBAgIQJ9uoX4VD+yxE4kvYpTgkpTANBgkqhkiG9w0BAQsFADB4
        MQswCQYDVQQGEwJHQjEPMA0GA1UEBxMGTG9uZG9uMQ8wDQYDVQQJEwZMb25kb24x
        LTArBgNVBAsTJElCTSBTdWl0ZSBMaWNlbnNlIFNlcnZpY2UgKEludGVybmFsKTEY
        MBYGA1UEAxMPc2xzLnNscy5pYm0uY29tMB4XDTIyMTEzMDEwNDMzMVoXDTQyMTEy
        NTEwNDMzMVoweDELMAkGA1UEBhMCR0IxDzANBgNVBAcTBkxvbmRvbjEPMA0GA1UE
        CRMGTG9uZG9uMS0wKwYDVQQLEyRJQk0gU3VpdGUgTGljZW5zZSBTZXJ2aWNlIChJ
        bnRlcm5hbCkxGDAWBgNVBAMTD3Nscy5zbHMuaWJtLmNvbTCCASIwDQYJKoZIhvcN
        AQEBBQADggEPADCCAQoCggEBAL3kzvcFvQBx0z/5HxBl2i+s6oGnhhNYiDF29+gh
        hkU8wMwH6eO+fIMJaTWx0qs3iU5zutC2/vxttb/CaVX5MCebYi0jmdDK0aQms5xR
        erXl+byvdB/qMeWyiSXvF4D4nkKKX/b7dkoT5cnfTXmUxvHZ2HyntMbYA1zCcjag
        TSE/nzY1bA9ulzhkgAg6755k+XVoU2c0uHxS98u3QrSrAr4iaRK56mJ2r7jVm9Ua
        0CKYLbefdw0JGS7iNcoEEs7lprZKUje9rj487P3qDlkWuQY9w8vwIY6R58UMrOai
        /UhVMeLXe2D/HWDl0xnvhNlxjJV2uRE8zVLBra3JPRrBQpcCAwEAAaNCMEAwDgYD
        VR0PAQH/BAQDAgIEMA8GA1UdEwEB/wQFMAMBAf8wHQYDVR0OBBYEFMkBnsDIZ6gy
        RTSgZYUU8C5/0sm2MA0GCSqGSIb3DQEBCwUAA4IBAQApGJsXE5TDa62m2jGUuKPm
        2RsDWsD3DArSHVthJbPkPRkzk+kTfgttJnmfaRGOS+xepKN+vgywIpt8SQcjNKR1
        Rd/Wz52+ZWCxlGTRBNxJKm5qDRxDryISqtFv7RYf6AqdmCclWE8CZ9auqax04c+W
        n3mnLI9C5O8G+l1yt7czOWktGjfCWNhcOBUC6bPiaRxjqGK/uWKomOFvByvvGTim
        zN3X4Jd1Yt7gn810CqG0HVIhw9FZVMr7BYvZWSEX8NxT/OgjM/d6/bdRM7ueSf9Z
        Bcb7G0DDftTDANCXz9W39E5/nRkJJr3JkFKcrkGfc1SwjEqD+q+6JWHoV0JW8PaQ
        -----END CERTIFICATE-----
